/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "config.h"
#include "platform.h"
#include "LL_API.h"
#include "PCA9555.h"


#include "queue.h"
#include "handlerIOTask.h"
#include "ethernet.h"



volatile uint32_t u32MiliCount = 0;
volatile uint32_t u32SecCount = 0;

static uint32_t  u32lastprint = 0;




queue_t *DP_RxQueue;
queue_t *DP_TxQueue;

static void SystemClock_Config();


static void setup();


uint8_t tmpval = 0;
char *hello ="hello thangnq\r\n";
int main(void) {
	setup();
	while (1) {
		handler_comdata();
		//handler_IO();
		if((uint32_t)(u32MiliCount - u32lastprint) >= 1000){
			u32lastprint = u32MiliCount;
		}
	}
}

static void setup() {
	SystemClock_Config();
	COM_DEBUG_init(115200);
	COM_RS485_init(9600);
	PRINT_AUTHOR_INFO();
	DP_RxQueue = queue_init(DP_RX_QUEUE_MAX_SIZE);
	DP_TxQueue = queue_init(DP_TX_QUEUE_MAX_SIZE);

	pin_init();
	ethernetInit();
	RJ45_IO_setup();
	RJ45_set_output(0xff);
	//handler_IO();
	LOG("Setup done\r\n");
}



static void SystemClock_Config() {

	LL_APB2_GRP1_EnableClock(LL_APB2_GRP1_PERIPH_SYSCFG);
	LL_APB1_GRP1_EnableClock(LL_APB1_GRP1_PERIPH_PWR);

	/** Disable the internal Pull-Up in Dead Battery pins of UCPD peripheral
	 */
	LL_SYSCFG_DisableDBATT(LL_SYSCFG_UCPD1_STROBE | LL_SYSCFG_UCPD2_STROBE);

	LL_FLASH_SetLatency(LL_FLASH_LATENCY_2);
	while (LL_FLASH_GetLatency() != LL_FLASH_LATENCY_2)
		;
	LL_RCC_HSE_Enable();
	while (LL_RCC_HSE_IsReady() != 1) {
	}
	/* Main PLL configuration and activation */
	LL_RCC_PLL_ConfigDomain_SYS(LL_RCC_PLLSOURCE_HSE, LL_RCC_PLLM_DIV_1, 16,
			LL_RCC_PLLR_DIV_2);
	LL_RCC_PLL_Enable();
	LL_RCC_PLL_EnableDomain_SYS();
	while (LL_RCC_PLL_IsReady() != 1) {
	}
	LL_RCC_SetSysClkSource(LL_RCC_SYS_CLKSOURCE_PLL);
	while (LL_RCC_GetSysClkSource() != LL_RCC_SYS_CLKSOURCE_STATUS_PLL) {
	}
	/* Set AHB prescaler*/
	LL_RCC_SetAHBPrescaler(LL_RCC_SYSCLK_DIV_1);
	/* Set APB1 prescaler*/
	LL_RCC_SetAPB1Prescaler(LL_RCC_APB1_DIV_1);
	SystemCoreClockUpdate();
	SysTick_Config(SystemCoreClock / 1000);
}
